apiVersion: v1
kind: Service
metadata:
 name: sc-loadbalancer
 labels:
   app: securitycheck
   namespace: dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: securitycheck
